#Настройки
settings:
  
  db:
    
    #Хост
    host: '127.0.0.1'
    #Пользователь
    user: 'root'
    #Пароль
    pass: 'password'
    #База
    base: 'base'
  
  #Лимиты
  #<group>: <limit>
  limits:
    
    #Дефолтное значение
    #Используется, если у игрока
    #группа, которой нет в списке
    default: 2
    
    #Другие группы
    vip: 3
    prem: 4
    admin: 10
  
  #Способности дракона
  abilities:
    
    #Разрушаемость
    break:
      1: 2
      2: 5
      3: 10
    
    #Буст здоровья
    health:
      1: 2.0
      2: 10.0
      3: 20.0
      
    #Буст урона
    damage:
      1: 1
      2: 2
      3: 3
    
    #Эффекты
    effects:
      - 'DAMAGE_RESISTANCE'
      - 'JUMP'
      - 'INCREASE_DAMAGE'
      - 'SPEED'
      - 'WATER_BREATHING'
    
#Сообщения
messages:
  
  #Информация по командам
  info: |-
    &r &r
    &r &c/mobs list &7- список прирученных животных.
    &r &c/mobs give <nick> &7- передать питомца игроку.
    &r &r
    &r &c/dragon info &7- информация о драконе.
    &r &c/dragon kill &7- убить дракона.
    &r &c/dragon trage <nick> &7- обменять дракона.
    &r &c/dragon tp &7- телепортация к дракону.
    &r &c/dragon get &7- переместить дракона.
    &r &r
  #Информация о драконе
  dragon-info: |-
    &r &r
    &r &aМесторасположение: &e<x> <y> <z>
    &r &aЗдоровье: <hp>
    &r &aУровень: <level>
    &r &aСпособности:
    &r &e<abilities>
    &r &r
  #Игрок достиг лимита питомцев
  limit: '&cВы достигли лимита питомцев.'
  #Задержка на кормление
  cooldown: '&cВы сможете снова покормить через &6<time> &cсекунд.'
  #Игрок передал питомца другому игроку
  give: '&aВы передали своего питомца.'
  #Игрок приручил животное
  tame: '&aВы приручили животное.'